<a href="https://colab.research.google.com/github/vaishnokumar/status_deep_learning/blob/main/00.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
import torch
print(torch.__version__)

2.3.0+cu121


**Introduction to Tensors**

In [ ]:
#Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# Get the Python number within a tensor (only works with one-element tensors)
scalar.item()

7

In [ ]:
#Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
vector[0]

tensor(7)

In [ ]:
#MATRIX
MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
#Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR[0][0][1]

tensor(2)

In [ ]:
TESNOR1 = torch.tensor([[[[1,2,3,4],
                           [5,6,7,8],
                            [9,0,5,3]]]])
TESNOR1

tensor([[[[1, 2, 3, 4],
          [5, 6, 7, 8],
          [9, 0, 5, 3]]]])

In [ ]:
TESNOR1.ndim

4

In [ ]:
TESNOR1.shape

torch.Size([1, 1, 3, 4])

### **Random Tensors**

In [ ]:
# create a random tensors of size (3, 4)

rand_ten = torch.rand(3, 4)
rand_ten

tensor([[0.9920, 0.1741, 0.0854, 0.4387],
        [0.7813, 0.0567, 0.0930, 0.0028],
        [0.5836, 0.7407, 0.1551, 0.1471]])

In [ ]:
rand_ten.ndim

2

In [ ]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### **Zeros and Ones**

In [ ]:
# create a tensor of all zeros
zero = torch.zeros(3, 4)
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
#create a tensor of all ones
one = torch.ones(3,4)
one

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Creating a range of tensors and tesnors-like

In [ ]:
#range
tensor_range = torch.arange(0,10)
tensor_range

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
tensor_range_step = torch.arange(0,10,2) #with added step at last
tensor_range_step

tensor([0, 2, 4, 6, 8])

In [ ]:
#tensor like
tensor_zeros_like = torch.zeros_like(tensor_range)
tensor_zeros_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
tensor_ones_like = torch.ones_like(tensor_range)
tensor_ones_like

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### **Tensor Datatypes**

In [ ]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [ ]:
to_float_16 = float_32_tensor.type(torch.float16)
to_float_16

tensor([3., 6., 9.], dtype=torch.float16)

### **Getting information from tensors**

In [ ]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.9844, 0.5131, 0.3773, 0.2007],
        [0.0022, 0.4427, 0.1248, 0.4412],
        [0.2066, 0.0538, 0.2993, 0.6383]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


### **Manipulating tensors (tensor operations)**

In [ ]:
tensor = torch.tensor([1,2,3])
add = tensor + 10
add

tensor([11, 12, 13])

In [ ]:
tensor = torch.tensor([1,2,3])
sub = tensor - 10
sub

tensor([-9, -8, -7])

In [ ]:
tensor = torch.tensor([1,2,3])
mul = tensor * 10
mul

tensor([10, 20, 30])

In [ ]:
tensor = torch.tensor([10,25,30])
div = tensor // 2
div

tensor([ 5, 12, 15])

### **Matrix Multiplication (Dot Product)**

In [ ]:
torch.matmul(tensor,tensor)

tensor(1625)

In [ ]:
# Shapes need to be in the right way
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will error)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
#Transpose

tensor_B = tensor_B.T

In [ ]:
res = torch.matmul(tensor_A, tensor_B)
res

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [ ]:
## Finding the min, max, sum, (tensor aggregation)

In [ ]:
x  = torch.arange(10,110,10)
x

tensor([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [ ]:
x.min()

tensor(10)

In [ ]:
x.max()

tensor(100)

In [ ]:
x.mean()

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [ ]:
x= x.type(torch.float32)

## You may find some methods such as torch.mean() require tensors to be in torch.float32 (the most common) or another specific datatype, otherwise the operation will fail.

In [ ]:
torch.mean(x)

tensor(55.)

In [ ]:
print(f"Sum: {x.sum()}")

Sum: 550.0


### **Positional min/max **


You can also find the index of a tensor where the max or minimum occurs with torch.argmax() and torch.argmin() respectively.

In [ ]:
x

tensor([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [ ]:
x.argmin()

tensor(0)

In [ ]:
x.argmax()

tensor(9)

### Reshaping, stacking, squeezing and unsqueezing

In [ ]:
#reshape
y = torch.arange(1.,10.)
y, y.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
y_reshaped = y.reshape(3,3)
y_reshaped.shape

torch.Size([3, 3])

In [ ]:
#view

Returns a view of the original tensor in a different shape but shares the same data as the original tensor.

In [ ]:
z = y.view(1, 9)
z,y

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# stacking
y_stacked = torch.stack([y,y], dim = 0)
y_stacked

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
#squeeze
r = torch.zeros(2, 1, 2, 1, 2)
r.shape

torch.Size([2, 1, 2, 1, 2])

In [ ]:
torch.squeeze(r).shape

torch.Size([2, 2, 2])

In [ ]:
#unsqueezing
x = torch.tensor([1, 2, 3, 4])

print(x)

torch.unsqueeze(x, 0)
print(f'{torch.unsqueeze(x, 0)}')

torch.unsqueeze(x, 1)
print(f'{torch.unsqueeze(x, 1)}')

tensor([1, 2, 3, 4])
tensor([[1, 2, 3, 4]])
tensor([[1],
        [2],
        [3],
        [4]])


In [ ]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


### Indexing

In [ ]:
x = torch.arange(1,10)
x = x.reshape(1,3,3)      # 1 > layer, 3 > row, 3 > column

In [ ]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0][0]

tensor([1, 2, 3])

In [ ]:
x[0][1][1]

tensor(5)

In [ ]:
x[0][2][2]

tensor(9)

In [ ]:
x[0][1:2][0][1:]

tensor([5, 6])

In [ ]:
ensor_3d = torch.tensor([[[1, 2, 3, 4],
                           [5, 6, 7, 8],
                           [9, 10, 11, 12]],

                          [[13, 14, 15, 16],
                           [17, 18, 19, 20],
                           [21, 22, 23, 24]]])

In [ ]:
ensor_3d

tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])

In [ ]:
ensor_3d[1,1:,2:]

tensor([[19, 20],
        [23, 24]])

In [ ]:
ensor_3d[1,1:2,3] = 99

In [ ]:
ensor_3d

tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 99],
         [21, 22, 23, 24]]])

In [ ]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
x[0,2,2]

tensor(9)

In [ ]:
x[0,:,2]

tensor([3, 6, 9])

In [ ]:
x.shape

torch.Size([1, 3, 3])

### Pytorch Tensors & Numpy

In [ ]:
# numpy array to torch
arr = np.arange(1, 8)
tensor = torch.from_numpy(arr)
arr,tensor

(array([1, 2, 3, 4, 5, 6, 7]), tensor([1, 2, 3, 4, 5, 6, 7]))

In [ ]:
arr.dtype,tensor.dtype

(dtype('int64'), torch.int64)

In [ ]:
tensor = tensor.type(torch.float32)

In [ ]:
tensor.dtype

torch.float32

In [ ]:
# tensor to numpy array
tensor = torch.ones(7)
numpy_to_tensor = tensor.numpy()
tensor,numpy_to_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducibility (trying to take the random out of random)

In [ ]:
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.2585, 0.5601, 0.3570, 0.1934],
        [0.2418, 0.4077, 0.1110, 0.4343],
        [0.7031, 0.2433, 0.9333, 0.1974]])

Tensor B:
tensor([[0.7321, 0.5723, 0.3230, 0.2583],
        [0.2296, 0.3588, 0.2849, 0.8146],
        [0.7913, 0.7289, 0.3219, 0.4856]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [ ]:
# # Set the random seed
RANDOM_SEED=42 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called
# Without this, tensor_D would be different to tensor_C
torch.random.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

###Running tensors on GPUs (and making faster computations)

In [ ]:
!nvidia-smi

Thu May 23 16:52:11 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   40C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [ ]:
# Check for GPU
import torch
torch.cuda.is_available()

True

In [ ]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# Count number of devices
torch.cuda.device_count()

1

Putting tensors (and models) on the GPU

In [ ]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])
# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

Moving tensors back to the CPU

In [ ]:
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [ ]:
# Instead, copy the tensor back to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [ ]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')