<a href="https://colab.research.google.com/github/vaishnokumar/status_deep_learning/blob/main/00_EX.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
torch.__version__

'2.3.0+cu121'

In [2]:
rand_ten = torch.rand(7, 7)
rand_ten

tensor([[0.2771, 0.5122, 0.2740, 0.9420, 0.9668, 0.8741, 0.9546],
        [0.8921, 0.3455, 0.0525, 0.7964, 0.1445, 0.0350, 0.8051],
        [0.4785, 0.1842, 0.0919, 0.9794, 0.6333, 0.4374, 0.5756],
        [0.0223, 0.6248, 0.5825, 0.6076, 0.5960, 0.3298, 0.5341],
        [0.0058, 0.9350, 0.1807, 0.8967, 0.6628, 0.3481, 0.1902],
        [0.3984, 0.5288, 0.5462, 0.4014, 0.3608, 0.7112, 0.2104],
        [0.8728, 0.6405, 0.3561, 0.9328, 0.1537, 0.7631, 0.9052]])

In [3]:
rand_ten1 = torch.rand(1, 7)
rand_ten2 = rand_ten1.T

In [4]:
rand_ten3 = torch.matmul(rand_ten, rand_ten2)
rand_ten3, rand_ten3.shape

(tensor([[3.3602],
         [2.0240],
         [2.3327],
         [2.3629],
         [2.2985],
         [2.3950],
         [3.3942]]),
 torch.Size([7, 1]))

In [5]:
random_seed = 0

torch.manual_seed(seed= random_seed)

rand1 = torch.rand(7, 7)

rand2 = torch.rand(1, 7)
rand3 = rand2.T

rand4 = torch.matmul(rand1, rand3)

rand4, rand4.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

In [6]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [16]:
torch.manual_seed(1234)

x = torch.rand(2,3).to(device)

y = torch.rand(2,3).to(device)

x,y

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))

In [20]:
z = torch.matmul(x, y.T)
z,z.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

In [21]:
z_max = torch.max(z)

z_min = torch.min(z)

z_max, z_min

(tensor(0.5617, device='cuda:0'), tensor(0.3647, device='cuda:0'))

In [22]:
arg_max = torch.argmax(z)

arg_min = torch.argmin(z)
arg_max, arg_min

(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))

In [27]:
torch.manual_seed(7)

new = torch.rand(1,1,1,10)

tensor_E = new.squeeze()

print(new, new.shape)
print(tensor_E, tensor_E.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
